### ISSUE TITLE
Missing rsources in FXMLExample and ScrollPaneExample examples

### ISSUE THREAD

**Issue by ltorok** [jjenkov/javafx-examples#5]
Hi,

in FXMLExample (fxml file) and ScrollPaneExample (jpg file) are missing resources.
Fix it, please.

Thanks.

**Comment by jjenkov** [comment]
I am just looking at JavaFX Drag and Drop. When I have added an example or two with drag and drop I will look at this issue and hopefully fix it.

**Comment by jjenkov** [comment]
This issue has now been fixed, so I will close this issue.

**Comment by jjenkov** [comment]
Ah, wait, only the FXMLExample's missing resource has been fixed. I will close this issue and create a new issue for the ScrollPane example that is missing a resource.

**Comment by jjenkov** [comment]
Issue is fixed for FXMLExample. A new issue has been created for ScrollPaneExample.
